import { metadataForPath } from "@/lib/seo/resolver"
import Link from "next/link"
import { ArrowUpRight, Mail, Phone } from "lucide-react"
import { PageHero } from "@/components/page-hero"
import { site } from "@/lib/site"
import { StructuredData } from "@/components/seo/structured-data"
import { buildPageEntityGraph } from "@/lib/seo/structured-data"
export const metadata = metadataForPath("/contact")
export default function ContactPage(){return <><StructuredData graph={buildPageEntityGraph("/contact", [{ label: "Home", href: "/" }, { label: "Contact", href: "/contact" }])} /><PageHero eyebrow="Start a conversation" title="Tell us what your floor needs." description="Phone and email are the fastest way to reach the team. Share a few details and we will help you figure out the right next step." image="/images/hero-kitchen.png" imageAlt="Bright kitchen with hardwood floors" breadcrumbs={[{label:"Home",href:"/"},{label:"Contact",href:"/contact"}]} /><main className="container mx-auto px-6 py-20 lg:py-28"><div className="grid gap-16 lg:grid-cols-[1.1fr_.9fr]"><section><p className="text-xs uppercase tracking-[0.2em] text-accent">Reach us directly</p><div className="mt-7 divide-y divide-border border-y border-border"><a href={site.phoneHref} className="flex items-center justify-between py-7 group"><span className="flex items-center gap-4"><Phone className="h-5 w-5 text-accent"/><span><span className="block text-sm text-muted-foreground">Call or text</span><span className="font-serif text-2xl group-hover:text-accent">{site.phone}</span></span></span><ArrowUpRight className="h-5 w-5"/></a><a href={site.emailHref} className="flex items-center justify-between py-7 group"><span className="flex items-center gap-4"><Mail className="h-5 w-5 text-accent"/><span><span className="block text-sm text-muted-foreground">Email us</span><span className="font-serif text-xl break-all group-hover:text-accent">{site.email}</span></span></span><ArrowUpRight className="h-5 w-5"/></a></div><Link href="/services" className="mt-8 inline-flex items-center gap-2 font-medium underline-offset-4 hover:underline">Review our services <ArrowUpRight className="h-4 w-4" /></Link></section><aside className="bg-secondary p-8 lg:p-10"><p className="text-xs uppercase tracking-[0.2em] text-accent">Where we work</p><h2 className="mt-3 font-serif text-3xl">Peoria and Central Illinois.</h2><p className="mt-5 leading-relaxed text-muted-foreground">We serve Peoria and surrounding communities within roughly 75 miles. If you are nearby and unsure whether we cover your project, call — we are happy to talk it through.</p></aside></div></main></>}
