"use client"

import { useMemo, useState } from "react"
import { Check, Eye, RotateCcw, Save, Search } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import type { ManagedSeoEntity } from "@/lib/seo/management"

export function SeoManagementClient({ initialEntities, canEdit }: { initialEntities: ManagedSeoEntity[]; canEdit: boolean }) {
  const [entities, setEntities] = useState(initialEntities)
  const [kind, setKind] = useState<"page" | "service">("page")
  const [search, setSearch] = useState("")
  const [selectedRoute, setSelectedRoute] = useState(initialEntities.find((entity) => entity.entity === "page")?.route ?? initialEntities[0]?.route ?? "")
  const [title, setTitle] = useState("")
  const [description, setDescription] = useState("")
  const [editing, setEditing] = useState(false)
  const [saving, setSaving] = useState(false)
  const [feedback, setFeedback] = useState<{ type: "success" | "error"; message: string } | null>(null)
  const visible = useMemo(() => entities.filter((entity) => entity.entity === kind && `${entity.route} ${entity.name} ${entity.title}`.toLowerCase().includes(search.toLowerCase())), [entities, kind, search])
  const selected = entities.find((entity) => entity.route === selectedRoute) ?? visible[0]

  function selectEntity(route: string) {
    const next = entities.find((entity) => entity.route === route)
    if (!next) return
    setSelectedRoute(route); setTitle(next.override?.title ?? next.fallbackTitle); setDescription(next.override?.description ?? next.fallbackDescription); setEditing(false); setFeedback(null)
  }
  function beginEdit() { if (!selected || !canEdit) return; setTitle(selected.override?.title ?? selected.fallbackTitle); setDescription(selected.override?.description ?? selected.fallbackDescription); setEditing(true); setFeedback(null) }
  async function save(action: "set" | "reset") {
    if (!selected || !canEdit) return
    setSaving(true); setFeedback(null)
    try {
      const response = await fetch("/api/admin/seo/management", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ route: selected.route, action, ...(action === "set" ? { fields: { title, description } } : {}) }) })
      const payload = await response.json() as { ok?: boolean; data?: { entity?: ManagedSeoEntity }; errors?: { message?: string }[] }
      if (!response.ok || !payload.ok || !payload.data?.entity) throw new Error(payload.errors?.[0]?.message ?? "Unable to save SEO settings.")
      setEntities((current) => current.map((entity) => entity.route === selected.route ? payload.data!.entity! : entity)); setEditing(false); setFeedback({ type: "success", message: action === "reset" ? "Override reset. The configured fallback is active." : "SEO override saved and reflected through the resolver." })
    } catch (error) { setFeedback({ type: "error", message: error instanceof Error ? error.message : "Unable to save SEO settings." }) } finally { setSaving(false) }
  }

  return <section aria-labelledby="management-heading" className="mt-10 border-t border-border pt-10">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><h2 id="management-heading" className="text-lg font-medium">Pages &amp; Services SEO management</h2><p className="mt-1 max-w-3xl text-sm text-muted-foreground">Only title and meta description overrides are editable. Canonical, indexability, governance, and service identity remain controlled by existing source systems.</p></div><Badge variant={canEdit ? "default" : "secondary"}>{canEdit ? "Editing enabled" : "Read only"}</Badge></div>
    <div className="mt-4 flex flex-wrap gap-2" role="tablist" aria-label="SEO entity type"><button type="button" role="tab" aria-selected={kind === "page"} onClick={() => { setKind("page"); const first = entities.find((entity) => entity.entity === "page"); if (first) selectEntity(first.route) }} className={`rounded-md border px-4 py-2 text-sm ${kind === "page" ? "border-foreground bg-foreground text-background" : "border-border hover:bg-secondary"}`}>Pages ({entities.filter((entity) => entity.entity === "page").length})</button><button type="button" role="tab" aria-selected={kind === "service"} onClick={() => { setKind("service"); const first = entities.find((entity) => entity.entity === "service"); if (first) selectEntity(first.route) }} className={`rounded-md border px-4 py-2 text-sm ${kind === "service" ? "border-foreground bg-foreground text-background" : "border-border hover:bg-secondary"}`}>Services ({entities.filter((entity) => entity.entity === "service").length})</button></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-[0.8fr_1.2fr]">
      <Card className="overflow-hidden"><CardHeader><CardTitle className="text-base">{kind === "page" ? "Public pages" : "Existing services"}</CardTitle><CardDescription>Search and select an entity to view its effective SEO values.</CardDescription><label className="relative mt-2 block"><span className="sr-only">Search {kind}s</span><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" aria-hidden="true" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={`Search ${kind}s`} className="h-10 w-full rounded-md border border-input bg-background pl-9 pr-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" /></label></CardHeader><CardContent className="max-h-[520px] overflow-y-auto p-0">{visible.map((entity) => <button type="button" key={entity.route} onClick={() => selectEntity(entity.route)} className={`block w-full border-t border-border px-5 py-4 text-left transition-colors hover:bg-secondary ${selected?.route === entity.route ? "bg-secondary" : ""}`}><span className="flex items-center justify-between gap-3"><span className="font-medium">{entity.name}</span><Badge variant={entity.override ? "default" : "secondary"}>{entity.override ? "Override" : "Inherited"}</Badge></span><span className="mt-1 block font-mono text-xs text-muted-foreground">{entity.route}</span><span className="mt-2 block text-xs text-muted-foreground">{entity.issueCount} audit issues · {entity.indexable ? "Indexable" : "Noindex"}</span></button>)}{!visible.length && <p className="p-6 text-sm text-muted-foreground">No matching {kind}s.</p>}</CardContent></Card>
      {selected ? <Card><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="text-base">{selected.name}</CardTitle><CardDescription className="mt-1 font-mono">{selected.route}</CardDescription></div><div className="flex gap-2"><Badge>{selected.indexable ? "Indexable" : "Noindex"}</Badge><Badge variant={selected.issueCount ? "destructive" : "secondary"}>{selected.issueCount} issues</Badge></div></div></CardHeader><CardContent className="space-y-6">
        <div className="border border-border bg-secondary/30 p-4"><div className="flex items-center gap-2 text-sm font-medium"><Eye className="h-4 w-4" aria-hidden="true" /> Effective SEO preview</div><p className="mt-4 text-lg font-medium text-blue-700">{editing ? title : selected.title}</p><p className="mt-1 font-mono text-xs text-emerald-700">https://peoriahardwoodfloors.com{selected.route}</p><p className="mt-2 text-sm text-muted-foreground">{editing ? description : selected.description}</p><p className="mt-3 text-xs text-muted-foreground">Preview only; this does not claim to represent actual Google rendering.</p></div>
        <div className="grid gap-5"><div><div className="flex items-center justify-between gap-3"><label htmlFor="seo-title" className="text-sm font-medium">SEO title</label><span className="text-xs text-muted-foreground">{(editing ? title : selected.title).length}/160</span></div>{editing ? <input id="seo-title" value={title} onChange={(event) => setTitle(event.target.value)} maxLength={160} className="mt-2 h-10 w-full rounded-md border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" /> : <p className="mt-2 rounded-md border border-border bg-secondary/30 p-3 text-sm">{selected.title}</p>}<p className="mt-1 text-xs text-muted-foreground">{selected.override?.title ? "Page/service override" : "Inherited from configured resolver fallback"}</p></div><div><div className="flex items-center justify-between gap-3"><label htmlFor="seo-description" className="text-sm font-medium">Meta description</label><span className="text-xs text-muted-foreground">{(editing ? description : selected.description).length}/320</span></div>{editing ? <textarea id="seo-description" value={description} onChange={(event) => setDescription(event.target.value)} maxLength={320} rows={4} className="mt-2 w-full rounded-md border border-input bg-background p-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" /> : <p className="mt-2 rounded-md border border-border bg-secondary/30 p-3 text-sm">{selected.description}</p>}<p className="mt-1 text-xs text-muted-foreground">{selected.override?.description ? "Page/service override" : "Inherited from configured resolver fallback"}</p></div></div>
        <div className="grid gap-3 rounded-md border border-border p-4 text-sm sm:grid-cols-2"><div><p className="text-xs uppercase tracking-wide text-muted-foreground">Read-only fields</p><p className="mt-2">Canonical: <span className="font-mono text-xs">{selected.canonical}</span></p><p className="mt-1">Indexability: {selected.indexable ? "Index" : "Noindex (governed)"}</p><p className="mt-1">Page purpose: {selected.pagePurpose ?? "Unavailable"}</p></div><div><p className="text-xs uppercase tracking-wide text-muted-foreground">Governance context</p><p className="mt-2">Primary topic: {selected.primaryTopic ?? "Unavailable"}</p><p className="mt-1">Search intent: {selected.searchIntent ?? "Unavailable"}</p><p className="mt-1">Local relevance: {selected.localRelevance}</p></div></div>
        {feedback && <p role="status" className={`flex items-center gap-2 text-sm ${feedback.type === "success" ? "text-emerald-700" : "text-destructive"}`}>{feedback.type === "success" && <Check className="h-4 w-4" aria-hidden="true" />}{feedback.message}</p>}
        <div className="flex flex-wrap gap-2">{!editing && <button type="button" onClick={beginEdit} disabled={!canEdit} className="inline-flex items-center gap-2 rounded-md bg-foreground px-4 py-2 text-sm font-medium text-background disabled:cursor-not-allowed disabled:opacity-50"><Save className="h-4 w-4" aria-hidden="true" />Edit supported fields</button>}{editing && <><button type="button" onClick={() => save("set")} disabled={saving || !title.trim() || !description.trim()} className="inline-flex items-center gap-2 rounded-md bg-foreground px-4 py-2 text-sm font-medium text-background disabled:cursor-not-allowed disabled:opacity-50"><Save className="h-4 w-4" aria-hidden="true" />{saving ? "Saving…" : "Save override"}</button><button type="button" onClick={() => { setEditing(false); selectEntity(selected.route) }} className="rounded-md border border-border px-4 py-2 text-sm">Cancel</button></>}{selected.override && <button type="button" onClick={() => save("reset")} disabled={saving || !canEdit} className="inline-flex items-center gap-2 rounded-md border border-border px-4 py-2 text-sm disabled:cursor-not-allowed disabled:opacity-50"><RotateCcw className="h-4 w-4" aria-hidden="true" />Reset override</button>}</div>
      </CardContent></Card> : <Card><CardContent className="p-8 text-sm text-muted-foreground">Select an entity to manage its supported SEO fields.</CardContent></Card>}
    </div>
  </section>
}
