import { existsSync } from "node:fs"
import { chmod, mkdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import { businessEntity, isLocationPublishable, serviceAreaRecords, serviceAreaStatement, type ServiceAreaType, type VerificationState } from "@/lib/seo/local"
import { CASE_STUDIES, CONTENT_GROWTH_LIFECYCLE, canPublishCaseStudy, validateCaseStudyRecord, type CaseStudyRecord, type ContentGrowthLifecycle, type GrowthAuditIssue } from "@/lib/seo/content-growth"
import { services } from "@/lib/site"
import { recordSeoChangeEvent } from "@/lib/seo/management"

const DATA_DIR = path.join(process.cwd(), "data")
const STORE_PATH = path.join(DATA_DIR, "seo-local-governance.json")
const SERVICE_AREA_TYPES: readonly ServiceAreaType[] = ["city", "county", "zip", "region", "radius"]
export type LocalReviewState = "unreviewed" | "reviewed" | "rejected"
export type LocalGovernanceRecord = {
  id: string
  name: string
  type: ServiceAreaType
  region?: string
  parent?: string
  slug?: string
  relatedServiceSlugs: string[]
  relationship: "verified-service-area" | "proposed-service-area" | "unsupported-location"
  verificationState: VerificationState
  sourceEvidence: string[]
  uniqueContentReady: boolean
  hasRealServiceContext: boolean
  pageEligible: boolean
  indexable: boolean
  contentStatus: "planning-only" | "draft" | "review"
  reviewStatus: LocalReviewState
  governanceIssues: string[]
}
export type CaseStudyManagementRecord = CaseStudyRecord & {
  title: string
  sourceMaterial: string[]
  requiredFactReview: string[]
  seoReviewRequirements: string[]
  contentStatus: ContentGrowthLifecycle
  reviewStatus: LocalReviewState
}
export type LocalGovernanceStore = { version: 1; businessPending: Record<string, string>; localRecords: LocalGovernanceRecord[]; caseStudies: CaseStudyManagementRecord[] }
export type LocalSnapshot = { business: typeof businessEntity; businessPending: Record<string, string>; serviceAreaStatement: string; serviceAreas: LocalGovernanceRecord[]; caseStudies: CaseStudyManagementRecord[] }
function emptyStore(): LocalGovernanceStore { return { version: 1, businessPending: {}, localRecords: [], caseStudies: [] } }
async function ensureDataDir() { if (!existsSync(DATA_DIR)) await mkdir(DATA_DIR, { recursive: true }) }
async function readStore(): Promise<LocalGovernanceStore> { try { const parsed = JSON.parse(await readFile(STORE_PATH, "utf8")); if (parsed?.version === 1 && Array.isArray(parsed.localRecords) && Array.isArray(parsed.caseStudies) && parsed.businessPending && typeof parsed.businessPending === "object") return parsed as LocalGovernanceStore } catch {} return emptyStore() }
async function writeStore(store: LocalGovernanceStore) { await ensureDataDir(); await writeFile(STORE_PATH, JSON.stringify(store, null, 2), "utf8"); try { await chmod(STORE_PATH, 0o600) } catch {} }

export async function getLocalSnapshot(): Promise<LocalSnapshot> { const store = await readStore(); return { business: businessEntity, businessPending: store.businessPending, serviceAreaStatement, serviceAreas: [...serviceAreaRecords.map((record) => ({ id: `code:${record.name}`, name: record.name, type: record.type, region: record.region, parent: record.parent, slug: record.slug, relatedServiceSlugs: [], relationship: record.verified ? "verified-service-area" : "proposed-service-area", verificationState: record.verified ? "verified" : "pending_verification", sourceEvidence: [], uniqueContentReady: false, hasRealServiceContext: false, pageEligible: record.pageEligible, indexable: false, contentStatus: "planning-only", reviewStatus: "unreviewed", governanceIssues: record.verified ? [] : ["This service area is not verified."] } as LocalGovernanceRecord)), ...store.localRecords], caseStudies: [...CASE_STUDIES.map((record) => ({ ...record, title: record.slug, sourceMaterial: [], requiredFactReview: [], seoReviewRequirements: [], contentStatus: record.publicationStatus === "published" ? "PUBLISHED" : "APPROVED", reviewStatus: record.humanApproval ? "reviewed" : "unreviewed" } as CaseStudyManagementRecord)), ...store.caseStudies] } }

function text(value: unknown) { return typeof value === "string" ? value.trim() : "" }
export function validateBusinessPending(input: unknown): { value?: Record<string, string>; error?: string } { if (!input || typeof input !== "object") return { error: "Business payload is required." }; const raw = input as Record<string, unknown>; const allowed = ["address", "openingHours", "googleBusinessProfileUrl", "facebookUrl", "instagramUrl", "awards", "memberships", "certifications", "affiliations", "reviewCount", "reviewRating", "testimonials", "foundedDate"] as const; const value: Record<string, string> = {}; for (const key of Object.keys(raw)) { if (!allowed.includes(key as typeof allowed[number])) return { error: `Unsupported business property: ${key}.` }; if (typeof raw[key] !== "string") return { error: `${key} must be plain text.` }; if (/[<>\u0000-\u001f]/.test(raw[key] as string)) return { error: `${key} contains unsafe characters.` }; value[key] = text(raw[key]); } for (const key of ["googleBusinessProfileUrl", "facebookUrl", "instagramUrl"] as const) if (value[key]) { try { const url = new URL(value[key]); if (!["https:"].includes(url.protocol)) return { error: `${key} must use HTTPS.` } } catch { return { error: `${key} must be a valid HTTPS URL.` } } } return { value } }

export function validateLocalRecord(input: unknown): { value?: LocalGovernanceRecord; error?: string } { if (!input || typeof input !== "object") return { error: "Local SEO payload is required." }; const raw = input as Record<string, unknown>; for (const key of ["id", "name"] as const) if (!text(raw[key])) return { error: `${key} is required.` }; if (!SERVICE_AREA_TYPES.includes(raw.type as ServiceAreaType)) return { error: "Unknown service-area type." }; if (!Array.isArray(raw.relatedServiceSlugs) || (raw.relatedServiceSlugs as unknown[]).some((slug) => typeof slug !== "string" || !services.some((service) => service.slug === slug))) return { error: "Every related service must be an existing service." }; if (!Array.isArray(raw.sourceEvidence) || (raw.sourceEvidence as unknown[]).some((item) => typeof item !== "string")) return { error: "Source evidence must be an array of plain text." }; if (!Array.isArray(raw.governanceIssues) || (raw.governanceIssues as unknown[]).some((item) => typeof item !== "string")) return { error: "Governance issues must be an array of plain text." }; const verificationState = raw.verificationState === "verified" ? "pending_verification" : raw.verificationState as VerificationState; if (!["draft", "pending_verification", "rejected", "archived"].includes(verificationState)) return { error: "Unsupported verification state." }; const verified = false; const eligible = false; return { value: { id: text(raw.id), name: text(raw.name), type: raw.type as ServiceAreaType, region: text(raw.region) || undefined, parent: text(raw.parent) || undefined, slug: text(raw.slug) || undefined, relatedServiceSlugs: raw.relatedServiceSlugs as string[], relationship: raw.relationship === "unsupported-location" ? "unsupported-location" : raw.relationship === "verified-service-area" ? "proposed-service-area" : "proposed-service-area", verificationState, sourceEvidence: raw.sourceEvidence as string[], uniqueContentReady: Boolean(raw.uniqueContentReady) && verified, hasRealServiceContext: Boolean(raw.hasRealServiceContext) && verified, pageEligible: eligible, indexable: false, contentStatus: raw.contentStatus === "review" ? "review" : raw.contentStatus === "draft" ? "draft" : "planning-only", reviewStatus: raw.reviewStatus === "reviewed" ? "reviewed" : raw.reviewStatus === "rejected" ? "rejected" : "unreviewed", governanceIssues: raw.governanceIssues as string[] } } }

export function localGovernanceIssues(record: LocalGovernanceRecord): string[] { const issues = [...record.governanceIssues]; if (record.relationship === "unsupported-location") issues.push("Unsupported location claims cannot become a public page."); if (record.verificationState !== "verified") issues.push("Verified relationship/evidence is required."); if (!record.uniqueContentReady) issues.push("Unique useful content is not ready."); if (!record.hasRealServiceContext) issues.push("A real service context is required."); if (!record.pageEligible) issues.push("Location publication gate is closed."); if (!record.indexable) issues.push("Indexability is not eligible."); return [...new Set(issues)] }
export function localIsPublishable(record: LocalGovernanceRecord) { return localGovernanceIssues(record).length === 0 && isLocationPublishable({ name: record.name, slug: record.slug ?? record.id, verified: false, pageEligible: false, uniqueContentReady: false, hasRealServiceContext: false, indexable: false, serviceSlugs: record.relatedServiceSlugs, verificationState: "pending_verification" }) }

function caseStudyBase(raw: Record<string, unknown>): CaseStudyManagementRecord { return { title: text(raw.title), slug: text(raw.slug), projectIdentifier: text(raw.projectIdentifier), projectType: text(raw.projectType), projectLocation: text(raw.projectLocation) ? { value: text(raw.projectLocation), verified: false } : undefined, servicePerformed: text(raw.servicePerformed), verifiedProjectDescription: text(raw.verifiedProjectDescription), projectImages: Array.isArray(raw.projectImages) ? raw.projectImages.filter((item): item is string => typeof item === "string") : [], factualProjectDetails: Array.isArray(raw.factualProjectDetails) ? raw.factualProjectDetails.filter((item): item is string => typeof item === "string") : [], documentedGoals: Array.isArray(raw.documentedGoals) ? raw.documentedGoals.filter((item): item is string => typeof item === "string") : [], documentedWorkPerformed: Array.isArray(raw.documentedWorkPerformed) ? raw.documentedWorkPerformed.filter((item): item is string => typeof item === "string") : [], documentedOutcome: text(raw.documentedOutcome) || undefined, materials: Array.isArray(raw.materials) ? raw.materials.filter((item): item is string => typeof item === "string") : [], finish: text(raw.finish) || undefined, approximateScope: text(raw.approximateScope) || undefined, timeline: text(raw.timeline) || undefined, clientApprovedQuote: text(raw.clientApprovedQuote) || undefined, beforeAfterImagery: raw.beforeAfterImagery === true, evidenceStatus: raw.evidenceStatus === "verified" ? "partial" : raw.evidenceStatus === "missing" ? "missing" : "partial", relatedServicePath: text(raw.relatedServicePath), publicationStatus: raw.publicationStatus === "published" ? "approved" : raw.publicationStatus === "approved" ? "approved" : "unpublished", humanApproval: false, sourceMaterial: Array.isArray(raw.sourceMaterial) ? raw.sourceMaterial.filter((item): item is string => typeof item === "string") : [], requiredFactReview: Array.isArray(raw.requiredFactReview) ? raw.requiredFactReview.filter((item): item is string => typeof item === "string") : [], seoReviewRequirements: Array.isArray(raw.seoReviewRequirements) ? raw.seoReviewRequirements.filter((item): item is string => typeof item === "string") : [], contentStatus: raw.contentStatus === "APPROVED" ? "APPROVED" : raw.contentStatus === "PUBLISHED" ? "APPROVED" : "BRIEF", reviewStatus: raw.reviewStatus === "reviewed" ? "reviewed" : "unreviewed" } }
export function validateCaseStudyInput(input: unknown): { value?: CaseStudyManagementRecord; error?: string; issues?: GrowthAuditIssue[] } { if (!input || typeof input !== "object") return { error: "Case-study payload is required." }; const raw = input as Record<string, unknown>; if (!text(raw.title) || !text(raw.slug) || !text(raw.relatedServicePath)) return { error: "Title, slug, and related service are required." }; if (!services.some((service) => `/services/${service.slug}` === raw.relatedServicePath)) return { error: "Related service must be an existing service route." }; const value = caseStudyBase(raw); const issues = validateCaseStudyRecord(value); if (value.publicationStatus === "approved" && (!value.humanApproval || !canPublishCaseStudy(value))) issues.push({ severity: "critical", code: "approval-gate-failed", message: "Case study requires verified evidence and human approval before approval." }); return { value, issues } }

export async function saveBusinessPending(value: Record<string, string>, actor: string) { const store = await readStore(); const previous = store.businessPending; store.businessPending = { ...store.businessPending, ...value }; await writeStore(store); await recordSeoChangeEvent({ id: crypto.randomUUID(), actor, timestamp: new Date().toISOString(), entity: "business", entityId: "canonical", field: "pending-fact", previousValue: JSON.stringify(previous), newValue: JSON.stringify(store.businessPending), action: "set", source: "seo-dashboard" }); return store.businessPending }
export async function saveLocalRecord(value: LocalGovernanceRecord, actor: string) { const store = await readStore(); const previous = store.localRecords.find((record) => record.id === value.id); store.localRecords = [...store.localRecords.filter((record) => record.id !== value.id), value]; await writeStore(store); await recordSeoChangeEvent({ id: crypto.randomUUID(), actor, timestamp: new Date().toISOString(), entity: "location", entityId: value.id, field: "record", previousValue: previous ? JSON.stringify(previous) : null, newValue: JSON.stringify(value), action: "set", source: "seo-dashboard" }); return value }
export async function saveCaseStudy(value: CaseStudyManagementRecord, actor: string) { const store = await readStore(); const previous = store.caseStudies.find((record) => record.slug === value.slug); store.caseStudies = [...store.caseStudies.filter((record) => record.slug !== value.slug), value]; await writeStore(store); await recordSeoChangeEvent({ id: crypto.randomUUID(), actor, timestamp: new Date().toISOString(), entity: "case-study", entityId: value.slug, field: "record", previousValue: previous ? JSON.stringify(previous) : null, newValue: JSON.stringify(value), action: "set", source: "seo-dashboard" }); return value }
