import { existsSync, readFileSync, readdirSync, statSync } from "node:fs"
import { chmod, mkdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import { CONTENT_SEO_RECORDS, indexableContentRecords, type ContentSeoRecord } from "@/lib/seo/content"
import { INTERACTIVE_ROUTE_POLICY, PUBLIC_STATIC_ROUTES, SEO_ROUTE_METADATA, canonicalUrl } from "@/lib/seo/resolver"
import { services } from "@/lib/site"
import { getSeoChangeHistory, recordSeoChangeEvent, type SeoChangeEvent } from "@/lib/seo/management"

export type ReviewState = "SUGGESTED" | "REVIEW" | "ACCEPTED" | "REJECTED" | "FLAGGED" | "APPROVED" | "DISMISSED"
export type InternalLinkRow = { id: string; sourceRoute: string; sourceEntity: string; targetRoute: string; targetEntity: string; context: string; relation: string; searchIntent: string; geographicRelevance: string; existing: boolean; status: "valid" | "blocked"; governanceIssues: string[]; reviewState: ReviewState }
export type OrphanRow = { route: string; pageType: string; indexable: boolean; inboundLinks: number; relatedTopic: string | null; relatedService: string | null; governanceState: string; opportunity: boolean }
export type ImageAltStatus = "missing" | "valid" | "generic" | "duplicate" | "too-long" | "keyword-stuffed" | "unavailable"
export type ImageRow = { id: string; assetPath: string; fileType: string; width: number | null; height: number | null; sizeBytes: number; altText: string | null; altStatus: ImageAltStatus; decorative: "unknown" | "informative" | "decorative"; sourcePage: string | null; ogStatus: "page-specific" | "inherited-fallback" | "not-configured"; reviewState: ReviewState; issues: string[] }
export type Phase07Snapshot = { internalLinks: InternalLinkRow[]; orphans: OrphanRow[]; images: ImageRow[]; history: SeoChangeEvent[]; unavailable: string[] }

type ReviewStore = { version: 1; linkReviews: Record<string, ReviewState>; imageReviews: Record<string, ReviewState> }
const DATA_DIR = path.join(process.cwd(), "data")
const REVIEW_PATH = path.join(DATA_DIR, "seo-phase-07-governance.json")
const PUBLIC_ORIGIN = "https://peoriahardwoodfloors.com"

function allPublicRoutes(): string[] { return [...new Set([...PUBLIC_STATIC_ROUTES, ...services.map((s) => `/services/${s.slug}`)])] }
function entityName(route: string): string { return route === "/" ? "Home" : route.split("/").filter(Boolean).pop()?.replace(/-/g, " ") ?? route }
function isPublicIndexable(route: string): boolean { return allPublicRoutes().includes(route) && !INTERACTIVE_ROUTE_POLICY[route as keyof typeof INTERACTIVE_ROUTE_POLICY] }
const REVIEW_STATES: readonly ReviewState[] = ["SUGGESTED", "REVIEW", "ACCEPTED", "REJECTED", "FLAGGED", "APPROVED", "DISMISSED"]
function isReviewState(value: unknown): value is ReviewState { return typeof value === "string" && REVIEW_STATES.includes(value as ReviewState) }
function safeReview(value: unknown, fallback: ReviewState = "SUGGESTED"): ReviewState { return isReviewState(value) ? value : fallback }
function readReviewStoreSync(): ReviewStore { try { const parsed = JSON.parse(readFileSync(REVIEW_PATH, "utf8")); if (parsed?.version === 1) return { version: 1, linkReviews: parsed.linkReviews ?? {}, imageReviews: parsed.imageReviews ?? {} } } catch {} return { version: 1, linkReviews: {}, imageReviews: {} } }
async function readReviewStore(): Promise<ReviewStore> { try { const parsed = JSON.parse(await readFile(REVIEW_PATH, "utf8")); if (parsed?.version === 1) return { version: 1, linkReviews: parsed.linkReviews ?? {}, imageReviews: parsed.imageReviews ?? {} } } catch {} return { version: 1, linkReviews: {}, imageReviews: {} } }
async function writeReviewStore(store: ReviewStore) { await mkdir(DATA_DIR, { recursive: true }); await writeFile(REVIEW_PATH, JSON.stringify(store, null, 2), "utf8"); try { await chmod(REVIEW_PATH, 0o600) } catch {} }

export function validateAltText(value: unknown): { value?: string; error?: string } {
  if (typeof value !== "string") return { error: "Alt text must be plain text." }
  const normalized = value.trim()
  if (/[<>\u0000-\u001f\u007f]/.test(normalized)) return { error: "Alt text contains unsafe markup or control characters." }
  if (normalized.length > 160) return { error: "Alt text must be 160 characters or fewer." }
  if (/\b(hardwood floor|flooring|peoria)\b.*\b(hardwood floor|flooring|peoria)\b/i.test(normalized)) return { error: "Alt text appears keyword-stuffed." }
  return { value: normalized }
}
export function classifyAltText(value: string | null, decorative = false): ImageAltStatus { if (decorative && value === "") return "valid"; if (value === null) return "unavailable"; const result = validateAltText(value); if (result.error?.includes("keyword")) return "keyword-stuffed"; if (!value.trim()) return "missing"; if (value.length > 120) return "too-long"; if (/^(image|photo|picture|img)[ _-]?\d*$/i.test(value.trim())) return "generic"; return result.error ? "generic" : "valid" }

function readJpegDimensions(file: string): { width: number; height: number } | null { try { const b = readFileSync(file); if (b[0] !== 0xff || b[1] !== 0xd8) return null; let i = 2; while (i + 9 < b.length) { if (b[i] !== 0xff) { i++; continue }; const marker = b[i + 1]; const length = b.readUInt16BE(i + 2); if ([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(marker)) return { height: b.readUInt16BE(i + 5), width: b.readUInt16BE(i + 7) }; i += 2 + length } } catch {} return null }
function imageDimensions(file: string, type: string): { width: number; height: number } | null { try { const b = readFileSync(file); if (type === "png" && b.length > 24 && b.toString("ascii", 1, 4) === "PNG") return { width: b.readUInt32BE(16), height: b.readUInt32BE(20) }; if (["jpg", "jpeg"].includes(type)) return readJpegDimensions(file) } catch {} return null }
function imageFiles(dir: string, prefix = ""): string[] { if (!existsSync(dir)) return []; return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => { const relative = path.posix.join(prefix, entry.name); if (entry.isDirectory()) return imageFiles(path.join(dir, entry.name), relative); return /\.(png|jpe?g|webp|gif|svg)$/i.test(entry.name) ? [relative] : [] }) }

export function buildInternalLinkRows(): InternalLinkRow[] {
  const reviews = readReviewStoreSync().linkReviews
  const validRoutes = new Set(allPublicRoutes())
  return CONTENT_SEO_RECORDS.flatMap((record) => record.internalLinks.map((link, index) => { const issues: string[] = []; if (link.href === record.path) issues.push("Self-link is not meaningful."); if (!validRoutes.has(link.href)) issues.push("Target is not an approved public route."); if (!isPublicIndexable(link.href)) issues.push("Target is noindex or not publicly indexable."); return { id: `${record.path}::${index}`, sourceRoute: record.path, sourceEntity: entityName(record.path), targetRoute: link.href, targetEntity: entityName(link.href), context: link.label, relation: link.relation, searchIntent: record.intent, geographicRelevance: record.geographicScope, existing: true, status: issues.length ? "blocked" : "valid", governanceIssues: issues, reviewState: safeReview(reviews[`${record.path}::${index}`], "ACCEPTED") } }))
}
export function buildOrphanRows(): OrphanRow[] { const rows = buildInternalLinkRows(); const inbound = new Map<string, number>(); for (const row of rows) if (row.status === "valid") inbound.set(row.targetRoute, (inbound.get(row.targetRoute) ?? 0) + 1); return indexableContentRecords().filter((record) => record.path !== "/").map((record) => ({ route: record.path, pageType: record.purpose, indexable: isPublicIndexable(record.path), inboundLinks: inbound.get(record.path) ?? 0, relatedTopic: record.primaryTopic, relatedService: record.path.startsWith("/services/") ? record.path : record.internalLinks.find((link) => link.relation === "related-service")?.href ?? null, governanceState: record.approval === "approved" && record.status === "published" ? "approved/published" : "not publishable", opportunity: (inbound.get(record.path) ?? 0) === 0 })) }
export function buildImageRows(): ImageRow[] { const reviews = readReviewStoreSync().imageReviews; const root = path.join(process.cwd(), "public"); return imageFiles(root).map((assetPath) => { const absolute = path.join(root, assetPath); const ext = path.extname(assetPath).slice(1).toLowerCase(); const dims = imageDimensions(absolute, ext); const id = `asset:${assetPath}`; const isOg = assetPath === "images/og-default.jpg"; const issues = dims ? [] : ["Dimensions are unavailable from the supported static metadata parser."]; return { id, assetPath: `/${assetPath}`, fileType: ext, width: dims?.width ?? null, height: dims?.height ?? null, sizeBytes: statSync(absolute).size, altText: null, altStatus: "unavailable", decorative: "unknown", sourcePage: null, ogStatus: isOg ? "inherited-fallback" : "not-configured", reviewState: safeReview(reviews[id], "FLAGGED"), issues } }) }
export async function getPhase07Snapshot(): Promise<Phase07Snapshot> { return { internalLinks: buildInternalLinkRows(), orphans: buildOrphanRows(), images: buildImageRows(), history: (await getSeoChangeHistory()).slice(0, 100), unavailable: ["Search Console inbound-link telemetry", "runtime image usage/alt associations not present in source contracts", "page-specific OG overrides beyond the resolver fallback"] } }
export function validateReviewMutation(input: unknown): { kind?: "link" | "image"; id?: string; state?: ReviewState; error?: string } { if (!input || typeof input !== "object") return { error: "Invalid request body." }; const raw = input as Record<string, unknown>; if (raw.kind !== "link" && raw.kind !== "image") return { error: "kind must be link or image." }; if (typeof raw.id !== "string" || !raw.id || raw.id.length > 240) return { error: "A bounded entity id is required." }; if (!isReviewState(raw.state)) return { error: "state must be an allowed review state." }; const state = raw.state; if (!(raw.kind === "link" ? buildInternalLinkRows().some((row) => row.id === raw.id) : buildImageRows().some((row) => row.id === raw.id))) return { error: "Unknown entity id." }; return { kind: raw.kind, id: raw.id, state }
}
export async function saveReview(kind: "link" | "image", id: string, state: ReviewState, actor: string) { const store = await readReviewStore(); const collection = kind === "link" ? store.linkReviews : store.imageReviews; const previous = collection[id] ?? null; collection[id] = state; await writeReviewStore(store); await recordSeoChangeEvent({ id: crypto.randomUUID(), actor, timestamp: new Date().toISOString(), entity: kind === "link" ? "page" : "page", entityId: id, field: "record", previousValue: previous, newValue: state, action: "set", source: "seo-dashboard" }); return { id, state } }
export function filterHistory(events: readonly SeoChangeEvent[], params: { entity?: string; action?: string; actor?: string; source?: string; search?: string; from?: string; to?: string; page?: number; pageSize?: number }): { items: SeoChangeEvent[]; page: number; pageSize: number; total: number } { const page = Math.max(1, Math.min(1000, Number(params.page) || 1)); const pageSize = Math.max(1, Math.min(50, Number(params.pageSize) || 25)); const search = params.search?.toLowerCase(); const filtered = events.filter((event) => (!params.entity || event.entity === params.entity) && (!params.action || event.action === params.action) && (!params.actor || event.actor === params.actor) && (!params.source || event.source === params.source) && (!params.from || event.timestamp >= params.from) && (!params.to || event.timestamp <= params.to) && (!search || `${event.entity} ${event.entityId} ${event.field}`.toLowerCase().includes(search))); return { items: filtered.slice((page - 1) * pageSize, page * pageSize), page, pageSize, total: filtered.length } }
export const phase07Canonical = (route: string) => canonicalUrl(route || PUBLIC_ORIGIN)
export const phase07RouteMetadata = SEO_ROUTE_METADATA
export type { ContentSeoRecord }
